v18.3 beta
steveseguin/vdo.ninja pull request #876
Opened 2021-06-15 08:56 UTC by steveseguin

fixed fade-ins and added transitions, plus a group of bug fixes.

2021-06-15 09:01 UTC, jcalado commented on index.html
> +				onclick="warnUser('For support, please browse https://reddit.com/r/obsninja or join the live chat on Discord at https://discord.vdo.ninja.\n\nThe Docs also contains many help guides and advanced
should `https://reddit.com/r/obsninja` be replaced with `https://reddit.com/r/vdoninja`?

2021-06-28 14:57 UTC, filiptronicek requested changes
👀

2021-06-28 14:57 UTC, filiptronicek commented on electron.html
> +		if (navigator.userAgent.toLowerCase().indexOf(' electron/') > -1) {
I think we could use `.includes()` here.
```suggestion
		if (navigator.userAgent.toLowerCase().includes(' electron/')) { 
```

2021-06-28 14:57 UTC, filiptronicek commented on electron.html
> +if ((location.hostname.toLowerCase() == "vdo.ninja") || (location.hostname.toLowerCase() == "obs.ninja")){
Using three equal sings will make this more reliable

```suggestion
if ((location.hostname.toLowerCase() === "vdo.ninja") || (location.hostname.toLowerCase() === "obs.ninja")){
```

2021-06-28 14:57 UTC, filiptronicek commented on convert.html
> +if (window.location.hostname.indexOf("vdo.ninja") == 0) {
Here, [eqeqeeq ](https://eslint.org/docs/rules/eqeqeq)should apply

```suggestion
if (window.location.hostname.indexOf("vdo.ninja") === 0) {

```

2021-06-30 18:17 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/steveseguin/vdo.ninja?pullRequest=876) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/steveseguin/vdo.ninja?pullRequest=876) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/steveseguin/vdo.ninja?pullRequest=876) it.</sub>

2021-07-09 06:39 UTC, merged